# Generated by Django 4.2.10 on 2024-03-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webpage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="debt",
            name="due_date",
            field=models.DateField(),
        ),
    ]
