# Generated by Django 4.2.10 on 2024-03-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webpage", "0002_alter_debt_due_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="debt",
            name="value",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="address",
            name="details",
            field=models.CharField(blank=True, default="", max_length=140),
        ),
    ]
