# Generated by Django 4.2.10 on 2024-03-25 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("webpage", "0003_debt_value_alter_address_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="webpage.address"
            ),
        ),
        migrations.AlterField(
            model_name="debtor",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="webpage.address"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="webpage.address"
            ),
        ),
    ]
