# Generated by Django 4.2.10 on 2024-04-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webpage", "0004_alter_company_address_alter_debtor_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="phone",
            field=models.CharField(default="", max_length=14),
        ),
        migrations.AddField(
            model_name="debt",
            name="last_contact",
            field=models.DateTimeField(default=""),
        ),
        migrations.AddField(
            model_name="debt",
            name="times_contacted",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="employee",
            name="role",
            field=models.CharField(
                choices=[
                    ("Owner", "Owner - All power"),
                    ("Admin", "Admin - Administrative"),
                    ("Worker", "Worker - Operation level"),
                ],
                default="Worker",
                max_length=70,
            ),
        ),
    ]
