# Generated by Django 4.2.10 on 2024-04-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "webpage",
            "0005_company_phone_debt_last_contact_debt_times_contacted_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="debt",
            name="last_contact",
            field=models.DateTimeField(default="1988-30-02 00:00"),
        ),
    ]
